### ISSUE TITLE
[FEAT] 아카이빙 뷰 UI 및 레이아웃 구현 

### ISSUE THREAD

**Issue by Suyeon9911** [The-Sopkathon-10/iOS#1]
## 💡 Feature Issue

아카이빙 뷰 ui 구현 ~~ 

## 🌿  To-do

- [ ] 유저 프로필 부분
- [ ] 아카이빙 테이블뷰 
- [ ] 아카이빙 테이블 뷰 셀 
- [ ] 유저 모델 만들기 
- [ ] 테이블 뷰 모델 만들기
