### ISSUE TITLE
[Feat] Popup 구현

### ISSUE THREAD

**Issue by cchanmi** [The-Sopkathon-10/iOS#2]
## 💡 Feature Issue

Custom View 구현

## 🌿  To-do

- [ ] UIView에 textField 구현하고, background 투명도 조절
- [ ] NO, YES 버튼 구현
- [ ] YES 버튼일 경우 textField 서버로 데이터 전달, NO 버튼일 경우 textfield 데이터 메인으로 이동
